# Generated by Django 6.0.3 on 2026-03-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_project_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="updated_at",
            new_name="created_at",
        ),
    ]
