# Generated by Django 6.0.3 on 2026-03-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_project_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
